# this is a java project using maven
language: java
jdk:
  - oraclejdk8
branches:
  only:
  - master
  - develop
  
install: mvn clean install -DskipTests -B dependency:resolve
script: find * && ./build/bin/opencga.sh --help
